[versions]
fastutil = "8.5.15"
joml = "1.10.8"

kotlin = "2.0.0"
dokka = "2.0.0"

[libraries]
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
joml = { module = "org.joml:joml", version.ref = "joml" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
spotless = { id = "com.diffplug.spotless", version = "7.2.1" }
