name: Deploy Dokka Documentation on GitHub Pages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate aggregated Dokka docs
        run: ./gradlew dokkaHtmlMultiModule

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokkaMultiModule

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
